import { ethers } from 'hardhat'
import { writeFileSync, mkdirSync } from 'fs'
import { resolve, dirname } from 'path'

async function main() {
  const Counter = await ethers.getContractFactory('Counter')
  const counter = await Counter.deploy()
  await counter.waitForDeployment()
  const address = await counter.getAddress()
  console.log('Counter:', address)

  // Write contract addresses to frontend/src/lib/contracts.ts
  const contractsPath = resolve(
    __dirname,
    '../../frontend/src/lib/contracts.ts'
  )
  const dir = dirname(contractsPath)
  mkdirSync(dir, { recursive: true })

  const content = `// Auto-generated by deploy script
export const contracts = {
  Counter: {
    address: "${address}",
    chainId: 31337,
  },
} as const;

export type ContractName = keyof typeof contracts;
`
  writeFileSync(contractsPath, content)
  console.log('Wrote contracts to', contractsPath)
}

main().catch(e => {
  console.error(e)
  process.exit(1)
})
