// Auto-generated by deploy script
export const contracts = {
  Counter: {
    address: "0x959922bE3CAee4b8Cd9a407cc3ac1C251C2007B1",
    chainId: 31337,
  },
} as const;

export type ContractName = keyof typeof contracts;
